name: flutter_application_3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1

  # File handling and PDF support
  file_picker: ^8.1.4
  pdf: ^3.11.1
  syncfusion_flutter_pdf: ^27.2.5
  dart_pdf_reader: ^0.5.0 

  # Payment gateway integration
  razorpay_flutter: ^1.3.5

  # UI/UX enhancements
  fluttertoast: ^8.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
